services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: alice
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wardrobe-social-app-test-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wardrobe-social-app-test-db
      SPRING_DATASOURCE_USERNAME: alice
      SPRING_DATASOURCE_PASSWORD: admin
volumes:
  postgres-data: