name: Java Spring Boot CI

on:
  push:
    branches:
      - dev # always push to dev first
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Generate test reports
        if: always()
        run: ./mvnw surefire-report:report-only

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/surefire-reports
            target/site

  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Run checkstyle
        run: ./mvnw checkstyle:check

      - name: Run SpotBugs
        run: ./mvnw spotbugs:check

      - name: SonarQube Scan
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw sonar:sonar -Dsonar.projectKey=wardrobe-social-app -Dsonar.organization=your-organization
        continue-on-error: true
