name: CI

on:
  push:
    branches:
      - dev  # Trigger on push to the dev branch
  pull_request:
    branches:
      - dev  # Run tests on pull requests to the dev branch

jobs:
  build:
    runs-on: ubuntu-latest  # Can choose another OS if needed

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Java version 21
          distribution: 'temurin'  # Using Temurin distribution

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
